import json

import streamlit as st
from ollama_client import open_stream

from logger import logger
from tools import tools, call_function
from prompt import SYSTEM_PROMPT


st.set_page_config(page_title="Dummy JSON Chatbot", page_icon="💬")
st.title("💬 Dummy JSON Chatbot")
st.write(
    "Ask about personal information, posts and to-dos of users. For example:"
    " `Get me the names and emails of users from California`,"
    " `How many users are there with blue eyes?`"
    " `Search a user named Sophia, get her posts and todos.`"
)
st.write(
    "**Warning:** The data used in this example is generated by [DummyJSON](https://dummyjson.com/docs)"
    " and does not represent real users."
)

if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "system", "content": SYSTEM_PROMPT}
    ]

for message in st.session_state.messages:
    if message["role"] == "system" or message["role"] == "tool":
        continue

    role = message["role"]
    content = message["content"]

    with st.chat_message(role):
        st.markdown(content)

if prompt := st.chat_input("Ask me about users..."):
    # Append user message to chat history
    st.session_state.messages.append(
        {"role": "user", "content": prompt}
    )
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        while True:
            stream = open_stream(st.session_state.messages, tools=tools)

            text_placeholder = st.empty()
            status_placeholder = st.empty()
            full_response = ""
            tool_calls = []

            for chunk in stream:
                if chunk.message.content:
                    full_response += chunk.message.content
                    text_placeholder.markdown(full_response)
                
                if chunk.message.tool_calls:
                    tool_calls.extend(chunk.message.tool_calls)

            logger.debug(f"Tool calls: {tool_calls}")
            if not tool_calls:
                text_placeholder.markdown(full_response)    
                st.session_state.messages.append(
                    {"role": "assistant", "content": full_response}
                )
                break

            with st.status("Agent is working...", state="running", expanded=True) as status:
                for tool_call in tool_calls:
                    func_name = tool_call.function.name
                    arguments = tool_call.function.arguments
                    args_text = ", ".join([f"{key}={value}" for key, value in arguments.items()])
                    st.write(f"**Calling tool:** {func_name}({args_text})")
                    data = call_function(func_name, arguments)
                    st.write(f"**Tool response:** {json.dumps(data, indent=2)}")

                    tool_call_msg = {
                        "role": "tool",
                        "tool_name": func_name,
                        "content": json.dumps(data),
                    }
                    st.session_state.messages.append(tool_call_msg)

                status.update(label=f"Step Completed: [{func_name}]", state="complete", expanded=False)
